services:
  swiss-tts-api:
    build:
      context: .
      target: backend
    container_name: swiss-tts-backend-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./audio_output:/app/audio_output

  swiss-tts-app:
    build:
      context: .
      target: frontend
    container_name: swiss-tts-mobile-app
    tty: true
    stdin_open: true
    ports:
      - "8081:8081"
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP}
      - EXPO_PUBLIC_API_IP=${HOST_IP}
      - NODE_OPTIONS=--no-warnings --experimental-specifier-resolution=node
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - swiss-tts-api
