[tools]
python = "3.12"
uv = 'latest'

# Automatic virtual environment
[env]
_.python.venv = { path = ".venv", create = true }
PROJECT_NAME = "{{ config_root | basename }}"
VIRTUAL_ENV = "{{ config_root }}/.venv"
PATH = "{{ config_root }}/.venv/bin:{{env.PATH}}"

[settings]
activate_aggressive = true

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Python: $(python --version)"
'''

# Tasks
[tasks.setup]
description = "Install dependencies using uv"
run = "uv sync"

[tasks.add]
description = "Add a new dependency"
run = "uv add {args}"

[tasks.update]
description = "Update dependencies"
run = "uv sync --upgrade"

[tasks.lint]
description = "Lint and check formatting with Ruff"
run = "uv run ruff check . && uv run ruff format --check ."

[tasks.format]
description = "Format and fix code with Ruff"
run = "uv run ruff format . && uv run ruff check --fix ."

[tasks.test]
description = "Run tests"
run = "uv run pytest"

[tasks.generate]
description = "Run the main application"
run = "uv run python -m src.swiss_tts.main"
